### ISSUE TITLE
ERROR: Couldn't find env file: /opt/smarthome/docker-compose/chronograf.env

### ISSUE THREAD

**Issue by andreas-bell** [IsarDomains/openhab-grafana-influxdb-chronograf#2]
hi,
I get the following error:
ERROR: Couldn't find env file: /opt/smarthome/docker-compose/chronograf.env

can you please commit the missing file ?
Rgds,
 Andreas

**Comment by IsarDomains** [comment]
Added missing file. However, it's just an empty placeholder because this project does not require to override any Chronograf configuration options so far.
Possible options can be found in the Chronograf documentation: https://docs.influxdata.com/chronograf/v1.8/administration/configuration/
